#!/usr/bin/env bash

read -rp "Do you really want to reconfigure everything destructively? [y|N] " resp
[[ ${resp,,} != y ]] && exit 0

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

scripts=(
  "$SCRIPT_DIR/config-scripts"
  "$SCRIPT_DIR/config-bash"
  "$SCRIPT_DIR/config-nvim"
  "$SCRIPT_DIR/config-tmux"
)

for script in "${scripts[@]}"; do
  # Skip if not executable
  [[ ! -x "$script" ]] && continue

  echo "running: $(basename "$script")"
  "$script"
done

