#!/usr/bin/env bash

read -rp "Do you really want to reconfigure everything destructively? [y|N] " resp
[[ ${resp,,} != y ]] && exit 0

cd "$DOTFILES" || cd dot || cd dotfiles || cd ../
scripts=("$(find -type f -name 'config-*' ! -name 'config-dot-all' -exec basename  {} \; -exec test -x {} \; | tail -n +2)")

for script in $scripts; do
  echo "running: $script"
  bash "$script"
done

