#!/bin/bash

# A bash script that helps me create notes for my blog

HOSTING_REPO="$REPOS/blog/"

# get_filename prompts the user for a filename
get_filename() {
	read -p "Enter a filename: " filename
}

# open_file creates and opens a file in the specified directory
open_file() {

	date=$(date +"%Y-%m-%d")
	timestamp="$(date +"%Y%m%d%H%m")"
	# Cd into the directory
	cd "$1" || exit
	# Create the file in the specified directory
	touch "$1/$filename.md"

	# Format the title by removing dashes
	title=$filename
	title="${title//-/ }"

	# set up the yaml frontmatter
	echo "---" >>"$1/$filename.md"
	echo "title: $filename" >>"$1/$filename.md"
	echo "date: $date" >>"$1/$filename.md"
	echo "tags:" >> "$1/$filename.md"

	# if [[ $2 = "zet" ]]; then
	# 	echo "tags:" >>"$1/$filename.md"
	# 	echo "- " >>"$1/$filename.md"
	# fi
	#
	# if [[ $2 = "post" ]]; then
	# 	echo "tags:" >>"$1/$filename.md"
	# 	echo "- Article" >>"$1/$filename.md"
	# fi

	echo "---" >>"$1/$filename.md"
	echo -en "\n" >>"$1/$filename.md"
	echo -en "\n" >>"$1/$filename.md"
	echo -en "\n" >>"$1/$filename.md"
	#echo "## Links:" >>"$1/$filename.md"
	#echo -en "\n" >>"$1/$filename.md"
	#echo "$timestamp" >>"$1/$filename.md"

	# Open the file in Neovim
	nvim -c 'normal G' "$1/$filename.md"

}

# Check the value of the first parameter
case "$1" in
# zet)
# 	# Call the function to get the filename
# 	get_filename
#
# 	# Call the function to create and open the file in the specified directory
# 	open_file "$REPOS/s/blog/content/zet" "zet"
#
# 	;;
post)
	# Call the function to get the filename
	get_filename

	# Call the function to create and open the file in the specified directory
	open_file "$REPOS/blog/content/posts" "post"
	;;

reset)
	rm -rf "$REPOS/blog/public"
	cd "$REPOS/blog/" || exit
	hugo
	hugo server --disableFastRender
	;;

pub)
	# ask for commit message, rebuild the site, push to blog repo, then push to hosting repo
	read -p "Enter commit message: " commitmessage

	# read -p "Would you like to tweet + toot that? (y/n) " will_tweet

	# if [[ $will_tweet == [Yy]* ]]; then
	# 	read -p "Enter tags, or press enter to post without tags: " tags
	# fi

	cd "$REPOS/blog" || exit
	rm -rf "$REPOS/blog/public"
	hugo
	git add .
	git commit -m "$commitmessage"
	git push
	rm -rf "$HOSTING_REPO*"
	cp -r "$REPOS"/blog/public/* "$HOSTING_REPO"
	cd "$HOSTING_REPO" || exit
	git add .
	git commit -m "$commitmessage"
	git push

	# if [[ $will_tweet == [Yy]* ]]; then
	# 	echo "Waiting 10 seconds to allow it to publish before tweeting."
	# 	sleep 10
	#
	# 	# post to twitter/mastodon without tags
	# 	if [[ $tags == "" ]]; then
	# 		tweet
	# 		toot
	# 		exit
	# 	fi
	# 	tweet "$tags"
	# 	toot "$tags"
	# fi
	;;

"")
	# Change to the websites/blog directory if no argument was given
	cd "$REPOS/blog" || exit
	;;

*)
	# Print an error message if the parameter was not used
	echo "Error: Invalid parameter. Usage: blog post|pub|reset"
	;;
esac

