#!/usr/bin/env bash

formatted_file_name=$(date "+%Y-%m-%d").md
echo ${formatted_file_name}
cd "$HOME/Documents/obsd" || exit

if [ "$1" = "work" ]; then
  touch "periodic-notes/daily/work/${formatted_file_name}"
  nvim "periodic-notes/daily/work/${formatted_file_name}"
else
  touch "periodic-notes/daily/${formatted_file_name}"
  nvim "periodic-notes/daily/${formatted_file_name}"
fi


# touch "periodic-notes/daily/${formatted_file_name}"
# nvim "periodic-notes/daily/${formatted_file_name}"
