#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g. on \"the wonderful thing about tiggers\"."
  exit 1
fi

cd "$HOME/Documents/obsd" || exit

if [ "$1" = "work" ]; then
  file_name=$(echo "$2" | tr ' ' '-')
  formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
  touch "notes/work/${formatted_file_name}"
  nvim "notes/work/${formatted_file_name}"
else
  file_name=$(echo "$1" | tr ' ' '-')
  formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
  touch "inbox/${formatted_file_name}"
  nvim "inbox/${formatted_file_name}"
fi
