#!/usr/bin/env bash

if [ -z "$1" ]; then
  echo "Error: A file name must be set, e.g. on \"the wonderful thing about tiggers\"."
  exit 1
fi

file_name=$(echo "$1" | tr ' ' '-')
formatted_file_name=$(date "+%Y-%m-%d")_${file_name}.md
if [[ $(uname -n) == "DTM017" ]]; then
    cd "/home/mrowe/Documents/obsd_h" || exit
fi
if [[ $(uname -n) == "wilco" ]]; then
    cd "/home/rwe/Documents/obsd" || exit
fi
if [ "$ODR" = "work" ]; then
    cd "/home/mrowe/docs/obsd_w" || exit
fi
touch "inbox/${formatted_file_name}"
nvim "inbox/${formatted_file_name}"
