#!/usr/bin/env bash

install-wezterm() {

	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install wezterm
		return
	fi

	if [[ $OSTYPE =~ ^msys || $(uname -r) =~ microsoft ]]; then
		winget.exe install --id wez.wezterm
		return
	fi

	if type apt-get &>/dev/null; then
          sudo apt-get isntall -y software-properties-common
          curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
          echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
          sudo apt -y update
          sudo apt install -y wezterm
          return
	fi

	echo "OS unsupported by this installer: $OSTYPE"

}

install-wezterm

