#!/usr/bin/env bash

install-neovim() {

	if [[ $OSTYPE =~ ^darwin ]]; then
		brew install neovim
		return
	fi

	# windows (git bash)
	if [[ $OSTYPE =~ ^msys ]]; then
		winget install --id neovim.neovim
		return
	fi

	# linux (old, but stable, no coc unfortunately)
	if type apt-get &>/dev/null; then
		curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
		sudo rm -rf /opt/nvim
		sudo tar -C /opt -xzf nvim-linux64.tar.gz
		return
	fi
	
	# linux (old, but stable, no coc unfortunately)
	if type dnf &>/dev/null; then
		curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
		sudo rm -rf /opt/nvim
		sudo tar -C /opt -xzf nvim-linux64.tar.gz
		return
	fi

	echo "OS unsupported by this installer: $OSTYPE"

}

type node || install-nodejs || exit 1
install-neovim
